### ISSUE TITLE
Error when installing the package

### ISSUE THREAD

**Issue by kalutheo** [inkuzmin/elm-multiselect#11]
Hi there !
After doing a `elm-package install inkuzmin/elm-multiselect` 

i am getting this error below : 

```
Detected errors in 1 module.
Problem in dependency inkuzmin/elm-multiselect 2.0.1

The elm-package.json constraints of 'inkuzmin/elm-multiselect' are probably
letting too much stuff through. Definitely open an issue on the relevant github
repo to get this fixed and save other people from this pain.

In the meantime, take a look through the direct dependencies of the broken
package and see if any of them have had releases recently. If you find the new
thing that is causing problems, you can artificially constrain things by adding
some extra constraints to your elm-package.json as a stopgap measure.
```

Any idea ?
Nice work by the way

**Comment by inkuzmin** [comment]
Hi, @kalutheo 
Thank you for contacting me! I haven't succeeded in reproducing the problem, but you may want to check this: https://github.com/inkuzmin/elm-multiselect/issues/2#issuecomment-320445421

**Comment by kalutheo** [comment]
Thanks @inkuzmin will try again

**Comment by aaronwhite** [comment]
Just ran into this as well; I checked out your 2nd comment @inkuzmin, not sure I understand, but for us:

Elm 0.18
Installed via command line ("elm package install inkuzmin/elm-multiselect")
Removed elm-stuff several times, did not fix

**Comment by inkuzmin** [comment]
Hi, @aaronwhite! That is interesting, I still can not reproduce it.
I would like to try to repeat the environment as closely as possible, can you confirm, please, that
`$ elm-package` results in `elm-package 0.18.0` and the same is true for `$ elm package`?

**Comment by aaronwhite** [comment]
Correct - both `elm-package` and `elm package` indicate `0.18.0`

**Comment by inkuzmin** [comment]
I have asked about this problem in the Slack channel, one nice idea was that it is possible that the error occurs when developers install other packages that have some of the same dependencies as elm-multiselect package but with non-overlapping version ranges. Can you check if this could be the case?

**Comment by aaronwhite** [comment]
I definitely plan to look back into this, just haven't had the chance just yet, but will follow up when I do

- Aaron
@aaronwhite
http://singularity.vc

Sent via Superhuman ( https://sprh.mn/?vip=aaron@singularity.vc )
