### ISSUE TITLE
menu not closing on outside click

### ISSUE THREAD

**Issue by nathanbraun** [inkuzmin/elm-multiselect#13]
Hi, great package, but I'm having trouble getting the menu to close when I click elsewhere on the screen.  I cloned your repo and ran using npm start and it worked correctly.  Any idea what might be wrong?  Not sure why the subscriptions to the keyboard events would be working, but not mouse.  Is the package on elm-lang up to date?  Thanks,

**Comment by inkuzmin** [comment]
Hi, @nathanbraun!
It should be up to date. It's hard to guess what could be the problem without the context (you may want to provide a code for reproducing the issue) but it could be useful to check if those lines of minimal example are reflected in your code (they are related to the task of closing the menu on out-of-component click):
https://github.com/inkuzmin/elm-multiselect/blob/eec1675e7af5e6f3b7d01544712419d2854a2e3c/example/src/MinimalExample.elm#L132-L137

**Comment by nathanbraun** [comment]
Thanks.  I realize it's tricky to help without seeing my code, but it's helpful to know the clicking is associated with these subscription related lines.  I'm trying to incorporate this multi-select in an app based off of @rtfeldman SPA example (https://github.com/rtfeldman/elm-spa-example)  so I must just not be forwarding and handling subscriptions correctly.  I'll play around with it.  Thanks!
