### ISSUE TITLE
upgrade to elm 0.19

### ISSUE THREAD

**Issue by nathanbraun** [inkuzmin/elm-multiselect#15]
Hi I'm currently using this in a production app, would love if it we could get a version for 0.19!

**Comment by inkuzmin** [comment]
Hi, thank you for your feedback! This package has dependencies that are (as far as I know) not 0.19-ready yet: elm-dom, elm-css. I am not sure it's possible to update it until they will be updated for their part. Please, correct me if I am wrong.

**Comment by zgohr** [comment]
`elm-dom` is now in [elm/browser](https://package.elm-lang.org/packages/elm/browser/latest) and `elm-css` you can use the [rc branch](https://github.com/rtfeldman/elm-css/releases) for now.

**Comment by peteralbert** [comment]
elm-css now fully supports elm 0.19. :-)

Thanks for the great work!

**Comment by inkuzmin** [comment]
@zgohr,
> elm-dom is now in elm/browser

Thanks for letting me know, I will check elm/browser!

@peteralbert,
> elm-css now fully supports elm 0.19

Awesome! I will try to make an update this weekend.

**Comment by h2000** [comment]
hi @inkuzmin 

Yesterday I started the upgrade for elm 0.19. and today I have a first working version. Only a small part of the styling is missing, because of the using of  Css.Foreign.selector from elm-css, which is not present in elm-css for 0.19.

Now I 'll will commit my branch and start a PR.

**Comment by inkuzmin** [comment]
Package was updated! Thanks to all of you for your contributions.

**Comment by h2000** [comment]
Cool! Thx a lot for the fast response.

**Comment by peteralbert** [comment]
Thanks a lot @inkuzmin !!!
