### ISSUE TITLE
How do I set the selected values?

### ISSUE THREAD

**Issue by Kurren123** [inkuzmin/elm-multiselect#18]
Lets say something happens that makes me want to set the selected values. How do I do that?

**Comment by inkuzmin** [comment]
Please, check this function, if I understood you correctly, it might do what you request for: https://package.elm-lang.org/packages/inkuzmin/elm-multiselect/latest/Multiselect#populateValues

Also this example could be relevant to your task: https://github.com/inkuzmin/elm-multiselect/blob/master/example/src/DynamicExample.elm
