### ISSUE TITLE
Unable to `make`

### ISSUE THREAD

**Issue by thedumbtechguy** [inkuzmin/elm-multiselect#2]
When I try running `elm-make`, I get the following error.

```shell
Problem in dependency inkuzmin/elm-multiselect 1.0.4

The elm-package.json constraints of 'inkuzmin/elm-multiselect' are probably
letting too much stuff through. Definitely open an issue on the relevant github
repo to get this fixed and save other people from this pain.

In the meantime, take a look through the direct dependencies of the broken
package and see if any of them have had releases recently. If you find the new
thing that is causing problems, you can artificially constrain things by adding
some extra constraints to your elm-package.json as a stopgap measure.

Detected errors in 1 module.
```

**Comment by inkuzmin** [comment]
@thedumbtechguy thank you very much for taking the time to write about this! I am going to investigate it now. I will reply you as soon as I will get the results.

**Comment by inkuzmin** [comment]
I tried to reproduce it, but with no success yet. Could you clarify some details for me, please?
- What version of Elm are you using?
- Do I understand correctly, that you got this message when you had been building a module that uses `elm-multiselect` like [here](https://github.com/inkuzmin/elm-multiselect/blob/master/example/src/MinimalExample.elm)?
- Could you try to remove `elm-stuff` folder from the path as well as `elm-package.json` and reinstall all the packages your module depends on with `elm-package install ...` (for `elm-multiselect` it would be `inkuzmin/elm-multiselect`)?
