### ISSUE TITLE
Allowing the user to enter in custom values

### ISSUE THREAD

**Issue by AlexanderLindsay** [inkuzmin/elm-multiselect#20]
I need a Tagging control, a multiselect where the user can enter their own values into the list, and this does everything I need but allowing the users to enter in their own values.

Is that a feature that should be added to this package? The minimum needed to support it would be an additional OutMsg that was sent when a user selected a value that didn't appear in the list of values. Only the enter key triggered selection would really work there but I think that might be ok.

Another way would be to have the user pass in a function that takes a value and turns it into a key value pair and maybe a boolean to indicate that it should support this functionality.

If this is something that fits into this package, I think I can create a pull request for the OutMsg method.

**Comment by inkuzmin** [comment]
@AlexanderLindsay 
sure, that's an awesome idea!

**Comment by inkuzmin** [comment]
This one is solved, thanks @AlexanderLindsay!
