### ISSUE TITLE
Dynamic population of values

### ISSUE THREAD

**Issue by dpinn** [inkuzmin/elm-multiselect#4]
I need to fetch values from a server using the input entered so far. I'd love a way to trigger dynamic population of the list of values.

Thank you for providing a very useful package.

**Comment by inkuzmin** [comment]
@dpinn thank you for your request! For the moment in my own project where I have a similar task I populate the list outside of the multi select control (by direct replacing of the model.myMultiselect with the new multiselect initialised with the fetched values). But I think you're right. Indeed, it would be nice to incorporate this into the control itself. I only need to check what is the best way to do it.

**Comment by inkuzmin** [comment]
Please, check `elm-multiselect/example/src/DynamicExample.elm` for the minimal example of dynamic population of values.
