### ISSUE TITLE
Update to elm-css 11.2.0 <= v < 12.0.0

### ISSUE THREAD

**Issue by xdumaine** [inkuzmin/elm-multiselect#5]
I'm trying to update to latest elm-css, but this package using 8.2.0 prevents that from working. I'm still very new to elm, but I'll help out if possible.

**Comment by inkuzmin** [comment]
@xdumaine, thank you for giving me know about the issue with the package! I've fixed dependencies, it should be fine now.

**Comment by xdumaine** [comment]
Thanks! This package worked well for me. We used it on our movie club's hobby site to filter genres of our movies.

**Comment by inkuzmin** [comment]
Awesome! Glad to know you found it useful.
