### ISSUE TITLE
Redundant .js leftovers in the repo?

### ISSUE THREAD

**Issue by mrapacz** [inkuzmin/elm-multiselect#6]
Hey,

first of all, thank you for providing the package, we're using it in our project and it works well! :+1: 

There is one issue we have, though.
Whenever I'm running our project and elm is compiling all of the assets the compilation takes around 10 seconds (usually it's done after around 2s). In the end it succeeds, but prints the following: 
```
iex(2)> [BABEL] Note: The code generator has deoptimised the styling of "web/elm/elm-stuff/packages/inkuzmin/elm-multiselect/1.0.4/docs/main.js" as it exceeds the max of "500KB".
```
Removing the file manually gets rid of the problem and the compilation time is normal once again. Is this file needed in the package? 

Thanks a lot!

**Comment by inkuzmin** [comment]
@mrapacz amazing! Yes, you are totally right, these files are redundant, like all the `docs` and `example` folders and their content (the first one is used only for generating of the GitHub demo page and the second one is just a collection of usage examples). I've just removed them, could you try [version 1.1.1](http://package.elm-lang.org/packages/inkuzmin/elm-multiselect/latest), please?

**Comment by mrapacz** [comment]
Works like a charm, thanks a lot for the help and really fast feedback! :1st_place_medal:
