### ISSUE TITLE
How to trigger a message after selecting a value  

### ISSUE THREAD

**Issue by cbenz** [inkuzmin/elm-multiselect#9]
Hi,

Thank you very much for your widget! It's very nice.

I'd like to trigger an HTTP request after I select a value in the widget. What's the best way to achieve it?

I thought I could do pattern-matching on the `subMsg` in `MultiselectMsg subMsg` (like [here](https://github.com/inkuzmin/elm-multiselect/blob/cf50ee92dc48444d45bd87bdc76d45fcb65dbaa0/example/src/MinimalExample.elm#L98-L103)), but the `Multiselect.elm` module does not export the constructors for its `Msg`.

My solution is to compare the previous selected values with the new ones, in this branch of the `update` function, but is there any better option?

Here is my code if it helps: https://git.nomics.world/dbnomics/dbnomics-ui/blob/9b7f3a2bbff748618f7c49091564e381a6d01f74/src/Page/Dataset.elm#L383-426

Thanks again!

**Comment by inkuzmin** [comment]
Hi @cbenz,
Thank you for contacting me! Your solution looks fine to me, I can't come with an idea how to do it better right now. But I will think about it, probably it is worth to consider exposing some facility to make it possible to accomplish the same result more elegantly.

**Comment by cbenz** [comment]
Thanks for replying so quickly :)

I think that the "Out message pattern" could be useful here.

Richard Feldman talks about it in his presentation at 43:53 https://youtu.be/DoA4Txr4GUs?t=43m53s

Some more links:
- https://medium.com/@_rchaves_/child-parent-communication-in-elm-outmsg-vs-translator-vs-nomap-patterns-f51b2a25ecb1
- http://folkertdev.nl/blog/elm-child-parent-communication/

Your code could define an `ExternalMsg` union type with a `Selected String` constructor and your update function could be `update -> Msg -> Model -> ( Model, Cmd Msg, ExternalMsg )`

**Comment by inkuzmin** [comment]
@cbenz,
Amazing! Thank you for providing references, I will definitely check them. I've been keeping "Elm Europe 2017" on my watch list for a long time now :-)

**Comment by inkuzmin** [comment]
Hi @cbenz!
Sorry for the delay, I had no chance to check the code until today. It seems that the new package was published successfully:
```
Verifying inkuzmin/elm-multiselect 2.0.0 ...
Version number 2.0.0 verified (MAJOR change, 1.1.3 => 2.0.0)
Success!
```
You may like to check the documentation for the introduced type: http://package.elm-lang.org/packages/inkuzmin/elm-multiselect/2.0.0/Multiselect#OutMsg
Also, the example provided was updated to demonstrate a way to deal with external messages: https://github.com/inkuzmin/elm-multiselect/blob/3a8dc089672b716e3f7c6c3e79840acdb503d790/example/src/Main.elm#L118-L134

**Comment by inkuzmin** [comment]
Thank you for your commit! I am sorry for this coordination failure, I have had to establish my plans clearer. If you don't mind making a pull request with the example file, it would be great to have it, because it could be tricky for users to figure out how to deal with the OutMsg pattern by looking at the current combined example with three widgets connected.
